### ISSUE TITLE
Allow evaluating models on Quantopian

### ISSUE THREAD

**Issue by maxnordlund** [riga/tfdeploy#14]
Hi, I came across this library when searching for ways to run neural networks on Quantopian. This is the closest one I could find that could run on their platform. However, since they only allow [certain libraries][1], some stuff will have to change.

This can hopefully be solved by guarding the imports, or make them conditional, for those modules that aren't allowed. Then it's the big one, encode the model as CSV, because sadly that is the only format they [support loading][2].

Those this sound good/doable?

[1]: https://www.quantopian.com/help#ide-module-import
[2]: https://www.quantopian.com/help#api-fetchcsv

**Comment by riga** [comment]
Hi maxnordlund,

correct me if I'm wrong, but I think the modules that aren't allowed on Quantopian are ``os`` and ``pickle``/``cPickle`` which seems a bit odd to me. ``pickle`` is used to serialize a model and save it to a file which makes it inevitable for tfdeploy. CSV can't be used for this purpose.

[``fetch_csv``](https://www.quantopian.com/help#api-fetchcsv) seems to be used for loading data, but you should consider tfdeploy models / model files as a container for your network / algorithm rather than a data source.

Hope this answers your questions.
